import { SourceDiscoveryScopeSchema } from "./source-discovery-contracts.js";
import type {
  OfficialAuthorityProfile,
  SourceDiscoveryScope,
} from "./source-discovery-contracts.js";

export class OfficialAuthorityProfileError extends Error {
  public constructor(
    message: string,
    public readonly retryable: boolean,
    public readonly code: string,
    options: { readonly cause?: unknown } = {},
  ) {
    super(message, options);
    this.name = "OfficialAuthorityProfileError";
  }
}

export interface OfficialSearchCandidate {
  readonly profile: OfficialAuthorityProfile;
  readonly sourceUrl: string;
  readonly sourceTitle: string;
  /** Evidence returned by the official authority search result itself. */
  readonly searchEvidence: string;
  readonly discoveryQuery: string;
}

function hasAllowedHost(url: URL, profile: OfficialAuthorityProfile): boolean {
  const host = url.hostname.toLowerCase();
  return profile.allowedHosts.some((allowed) =>
    allowed.startsWith(".") ? host.endsWith(allowed) : host === allowed,
  );
}

function hasAllowedResultHost(url: URL, profile: OfficialAuthorityProfile): boolean {
  const hosts =
    profile.resultUrlAllowlist !== undefined && profile.resultUrlAllowlist.length > 0
      ? profile.resultUrlAllowlist
      : profile.allowedHosts;
  const host = url.hostname.toLowerCase();
  return hosts.some((allowed) =>
    allowed.startsWith(".") ? host.endsWith(allowed) : host === allowed,
  );
}

/**
 * Strict egress guard shared by the discovery search and document acquisition
 * tools. A profile can add an official domain, but it cannot enable HTTP,
 * credentials, alternate ports, relative protocol tricks, or redirects.
 */
export function assertOfficialAuthorityUrl(value: string, profile: OfficialAuthorityProfile): URL {
  let url: URL;
  try {
    url = new URL(value);
  } catch (error) {
    throw new OfficialAuthorityProfileError(
      "Official authority URL is invalid",
      false,
      "URL_INVALID",
      {
        cause: error,
      },
    );
  }
  if (
    url.protocol !== "https:" ||
    url.username.length > 0 ||
    url.password.length > 0 ||
    url.port.length > 0 ||
    url.hash.length > 0 ||
    !hasAllowedHost(url, profile)
  ) {
    throw new OfficialAuthorityProfileError(
      "Official authority URL is outside the configured profile",
      false,
      "URL_NOT_OFFICIAL",
    );
  }
  return url;
}

/** Result/document links can be narrowed below the authority search host set. */
export function assertOfficialAuthorityResultUrl(
  value: string,
  profile: OfficialAuthorityProfile,
): URL {
  const url = assertOfficialAuthorityUrl(value, profile);
  if (!hasAllowedResultHost(url, profile)) {
    throw new OfficialAuthorityProfileError(
      "Official authority result URL is outside the configured result allowlist",
      false,
      "URL_NOT_OFFICIAL",
    );
  }
  return url;
}

function quotedSparqlLiteral(value: string): string {
  return value.replace(/[\\"\r\n]/gu, (character) => {
    if (character === "\\") return "\\\\";
    if (character === '"') return '\\"';
    return " ";
  });
}

function boundedTerms(scope: SourceDiscoveryScope): readonly string[] {
  return [scope.productCategory, ...scope.requiredTopics]
    .map((value) => value.replace(/\s+/gu, " ").trim())
    .filter(Boolean)
    .slice(0, 12);
}

function boundedTopicTerms(scope: SourceDiscoveryScope): string {
  return scope.requiredTopics
    .map((value) => value.replace(/\s+/gu, " ").trim())
    .filter(Boolean)
    .slice(0, 12)
    .join(" ")
    .slice(0, 600);
}

/**
 * This remains a closed, deterministic transformation. The profile template
 * is validated at the contract boundary and can interpolate only bounded
 * scope values; it is never evaluated as a URL, code, or model prompt.
 */
function configuredSearchTerms(
  profile: OfficialAuthorityProfile,
  scope: SourceDiscoveryScope,
): string {
  if (profile.queryTemplate === undefined) {
    return boundedTerms(scope).join(" ").slice(0, 800);
  }
  const language = scope.language.split("-", 1)[0]?.toLowerCase() ?? "en";
  const replacements: Readonly<Record<string, string>> = {
    topics: boundedTopicTerms(scope),
    productCategory: scope.productCategory.replace(/\s+/gu, " ").trim().slice(0, 240),
    language,
  };
  const terms = profile.queryTemplate
    .replace(
      /\{(topics|productCategory|language)\}/gu,
      (_match, key: string) => replacements[key] ?? "",
    )
    .replace(/\s+/gu, " ")
    .trim()
    .slice(0, 800);
  return terms || boundedTerms(scope).join(" ").slice(0, 800);
}

/**
 * This query is intentionally generated by code, not by a model. The profile
 * only selects the known Cellar endpoint; dynamic user terms are escaped as a
 * SPARQL literal and can never change graph structure or add an endpoint.
 */
function eurLexSparqlQuery(scope: SourceDiscoveryScope, limit: number): string {
  const terms = boundedTerms(scope).join(" ").slice(0, 600);
  const language = scope.language.split("-", 1)[0]?.toLowerCase() ?? "en";
  return [
    "PREFIX dct: <http://purl.org/dc/terms/>",
    "SELECT DISTINCT ?url ?title WHERE {",
    "  ?url dct:title ?title .",
    `  FILTER(langMatches(lang(?title), "${quotedSparqlLiteral(language)}"))`,
    `  FILTER(CONTAINS(LCASE(STR(?title)), LCASE("${quotedSparqlLiteral(terms)}")))`,
    "}",
    `LIMIT ${String(limit)}`,
  ].join("\n");
}

export interface OfficialAuthoritySearchRequest {
  readonly url: URL;
  readonly method: "GET";
  readonly headers: Readonly<Record<string, string>>;
  readonly discoveryQuery: string;
}

/**
 * Builds one request against a configured official endpoint. There is no
 * generic web-search endpoint, URL field, or LLM-generated query anywhere in
 * this capability.
 */
export function buildOfficialAuthoritySearchRequest(input: {
  readonly profile: OfficialAuthorityProfile;
  readonly scope: SourceDiscoveryScope;
}): OfficialAuthoritySearchRequest {
  const scope = SourceDiscoveryScopeSchema.parse(input.scope);
  const endpoint = assertOfficialAuthorityUrl(input.profile.searchEndpoint, input.profile);
  const terms = configuredSearchTerms(input.profile, scope);
  if (!terms) {
    throw new OfficialAuthorityProfileError(
      "Discovery scope has no safe search terms",
      false,
      "SEARCH_TERMS_MISSING",
    );
  }
  if (input.profile.searchMode === "EURLEX_CELLAR_SPARQL") {
    endpoint.searchParams.set("query", eurLexSparqlQuery(scope, input.profile.resultLimit));
    endpoint.searchParams.set("format", "application/sparql-results+json");
    return {
      url: endpoint,
      method: "GET",
      headers: { Accept: "application/sparql-results+json" },
      discoveryQuery: terms,
    };
  }
  endpoint.searchParams.set(input.profile.queryParameter ?? "q", terms);
  return {
    url: endpoint,
    method: "GET",
    headers: {
      Accept:
        input.profile.searchMode === "OFFICIAL_SEARCH_JSON"
          ? "application/json"
          : "text/html,application/xhtml+xml",
    },
    discoveryQuery: terms,
  };
}

function normalizedTitle(value: unknown, fallback: string): string {
  if (typeof value !== "string") return fallback;
  const normalized = value.replace(/\s+/gu, " ").trim();
  return normalized.slice(0, 500) || fallback;
}

function plainText(value: string): string {
  return value
    .replace(/<[^>]*>/gu, " ")
    .replace(/&nbsp;/giu, " ")
    .replace(/&amp;/giu, "&")
    .replace(/&quot;/giu, '"')
    .replace(/&#39;/giu, "'")
    .replace(/\s+/gu, " ")
    .trim();
}

function safeResultUrl(
  value: unknown,
  baseUrl: URL,
  profile: OfficialAuthorityProfile,
): string | null {
  if (typeof value !== "string" || value.trim().length === 0 || value.length > 2_048) return null;
  try {
    return assertOfficialAuthorityResultUrl(
      new URL(value.trim(), baseUrl).toString(),
      profile,
    ).toString();
  } catch {
    return null;
  }
}

function fieldsFromRecord(record: Record<string, unknown>, names: readonly string[]): unknown[] {
  return names.flatMap((name) => (name in record ? [record[name]] : []));
}

function jsonSearchCandidates(input: {
  readonly response: unknown;
  readonly profile: OfficialAuthorityProfile;
  readonly baseUrl: URL;
  readonly discoveryQuery: string;
}): readonly OfficialSearchCandidate[] {
  const urlFields = input.profile.resultUrlFields ?? [
    "url",
    "canonicalUrl",
    "pdfUrl",
    "href",
    "link",
  ];
  const titleFields = input.profile.resultTitleFields ?? ["title", "name", "label"];
  const candidates: OfficialSearchCandidate[] = [];
  const queue: unknown[] = [input.response];
  const seenObjects = new Set<object>();
  const seenUrls = new Set<string>();
  while (queue.length > 0 && candidates.length < input.profile.resultLimit) {
    const current = queue.shift();
    if (Array.isArray(current)) {
      for (const value of current.slice(0, 200) as readonly unknown[]) {
        queue.push(value);
      }
      continue;
    }
    if (typeof current !== "object" || current === null) continue;
    if (seenObjects.has(current)) continue;
    seenObjects.add(current);
    const record = current as Record<string, unknown>;
    const title = normalizedTitle(
      fieldsFromRecord(record, titleFields).find(
        (value): value is string => typeof value === "string",
      ),
      "Official normative source",
    );
    for (const value of fieldsFromRecord(record, urlFields)) {
      const sourceUrl = safeResultUrl(value, input.baseUrl, input.profile);
      if (sourceUrl === null || seenUrls.has(sourceUrl)) continue;
      seenUrls.add(sourceUrl);
      candidates.push({
        profile: input.profile,
        sourceUrl,
        sourceTitle: title,
        searchEvidence: title,
        discoveryQuery: input.discoveryQuery,
      });
      if (candidates.length >= input.profile.resultLimit) break;
    }
    for (const value of Object.values(record)) {
      if (typeof value === "object" && value !== null) queue.push(value);
    }
  }
  return candidates;
}

function sparqlSearchCandidates(input: {
  readonly response: unknown;
  readonly profile: OfficialAuthorityProfile;
  readonly baseUrl: URL;
  readonly discoveryQuery: string;
}): readonly OfficialSearchCandidate[] {
  const bindings =
    typeof input.response === "object" &&
    input.response !== null &&
    "results" in input.response &&
    typeof (input.response as { readonly results?: unknown }).results === "object" &&
    (input.response as { readonly results?: { readonly bindings?: unknown } }).results?.bindings;
  if (!Array.isArray(bindings)) return [];
  const candidates: OfficialSearchCandidate[] = [];
  const seen = new Set<string>();
  for (const binding of bindings.slice(0, input.profile.resultLimit * 3)) {
    if (typeof binding !== "object" || binding === null || Array.isArray(binding)) continue;
    const record = binding as Record<string, unknown>;
    const scalar = (key: string): string | null => {
      const value = record[key];
      if (typeof value !== "object" || value === null || Array.isArray(value)) return null;
      const nested = (value as Record<string, unknown>)["value"];
      return typeof nested === "string" ? nested : null;
    };
    const sourceUrl = safeResultUrl(
      scalar("url") ?? scalar("work") ?? scalar("document") ?? scalar("uri"),
      input.baseUrl,
      input.profile,
    );
    if (sourceUrl === null || seen.has(sourceUrl)) continue;
    seen.add(sourceUrl);
    const title = normalizedTitle(scalar("title"), "Official EUR-Lex source");
    candidates.push({
      profile: input.profile,
      sourceUrl,
      sourceTitle: title,
      searchEvidence: title,
      discoveryQuery: input.discoveryQuery,
    });
    if (candidates.length >= input.profile.resultLimit) break;
  }
  return candidates;
}

function htmlSearchCandidates(input: {
  readonly markup: string;
  readonly profile: OfficialAuthorityProfile;
  readonly baseUrl: URL;
  readonly discoveryQuery: string;
}): readonly OfficialSearchCandidate[] {
  const candidates: OfficialSearchCandidate[] = [];
  const seen = new Set<string>();
  const anchor =
    /<a\b[^>]*\bhref\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))[^>]*>([\s\S]*?)<\/a\s*>/giu;
  for (const match of input.markup.matchAll(anchor)) {
    if (candidates.length >= input.profile.resultLimit) break;
    const sourceUrl = safeResultUrl(match[1] ?? match[2] ?? match[3], input.baseUrl, input.profile);
    if (sourceUrl === null || seen.has(sourceUrl)) continue;
    const title = normalizedTitle(plainText(match[4] ?? ""), "Official normative source");
    if (title === "Official normative source") continue;
    seen.add(sourceUrl);
    candidates.push({
      profile: input.profile,
      sourceUrl,
      sourceTitle: title,
      searchEvidence: title,
      discoveryQuery: input.discoveryQuery,
    });
  }
  return candidates;
}

/** Parse only links delivered by a configured authority endpoint. */
export function parseOfficialAuthoritySearchResponse(input: {
  readonly profile: OfficialAuthorityProfile;
  readonly request: OfficialAuthoritySearchRequest;
  readonly body: string;
}): readonly OfficialSearchCandidate[] {
  if (input.profile.searchMode === "OFFICIAL_SEARCH_HTML") {
    return htmlSearchCandidates({
      markup: input.body,
      profile: input.profile,
      baseUrl: input.request.url,
      discoveryQuery: input.request.discoveryQuery,
    });
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(input.body) as unknown;
  } catch (error) {
    throw new OfficialAuthorityProfileError(
      "Official authority search did not return valid JSON",
      false,
      "SEARCH_RESPONSE_INVALID",
      { cause: error },
    );
  }
  if (input.profile.searchMode === "EURLEX_CELLAR_SPARQL") {
    return sparqlSearchCandidates({
      response: parsed,
      profile: input.profile,
      baseUrl: input.request.url,
      discoveryQuery: input.request.discoveryQuery,
    });
  }
  return jsonSearchCandidates({
    response: parsed,
    profile: input.profile,
    baseUrl: input.request.url,
    discoveryQuery: input.request.discoveryQuery,
  });
}

/**
 * Basic BCP-47 language matching for a profile's official-language coverage.
 * A generic language profile (`it`) supports a regional analysis (`it-IT`),
 * but a portal with only another language never becomes an implicit fallback.
 */
function profileSupportsScopeLanguage(
  profile: OfficialAuthorityProfile,
  scope: SourceDiscoveryScope,
): boolean {
  const primarySubtag = (value: string): string | null => {
    const normalized = value.trim().toLowerCase();
    if (!/^[a-z]{2,3}(?:-[a-z0-9]{2,8})*$/u.test(normalized)) return null;
    return normalized.split("-", 1)[0] ?? null;
  };
  const requested = primarySubtag(scope.language);
  return (
    requested !== null &&
    profile.languages.some((language) => primarySubtag(language) === requested)
  );
}

/** A country profile applies only to its chosen market; EU is additive. */
export function profileAppliesToScope(
  profile: OfficialAuthorityProfile,
  scope: SourceDiscoveryScope,
): boolean {
  if (!profile.active || !profileSupportsScopeLanguage(profile, scope)) return false;
  if (profile.jurisdictionCode === "EU") return scope.regulatoryAreas.includes("EU");
  return profile.jurisdictionCode === scope.marketCountryCode;
}
